---
title: "mack_creek"
format: html
execute:
  warning: FALSE
---

```{r}
library(tidyverse)
library(here)
library(janitor)
library(ggthemes)
```


```{r}
mack_verts <- read_csv(here::here("data", "AS00601.csv"))
mack_verts <- mack_verts |> janitor::clean_names()
head(mack_verts)
```
```{r}
mc_wt_5 <- mack_verts$weight[5]
mc_length_8_20 <- mack_verts$length1[8:20]
mc_dates <- c(mack_verts$sampledate)
```

```{r}
# subsetting out the giant salamanders
mc_salamanders <- mack_verts |> dplyr::filter(species == "DITE")
mc_salamanders
```

```{r}
salamander_size_plot <- ggplot(mc_salamanders, aes(x = length1, y = weight))+
  geom_point(color = "blue")+
  labs(title = "Salamander Snout Length vs. Weight", x = "Snout-Vent Length (mm)", y = "Weight (g)", caption = "Gregory, S.V. and I. Arismendi. 2020. https://doi.org/10.6073/pasta/7c78d662e847cdbe33584add8f809165") +
  theme_solarized()
salamander_size_plot

ggsave(here::here("figs", "salamander_size_plot.png"))
```
```{r}
mc_trout <- mack_verts |> filter(species == "ONCL")

```

```{r}
cutthroat_size <- ggplot(mc_trout, aes(x = length1, y = weight, color = reach)) +
  geom_point() +
  labs(title = "Trout Length by Weight", x = "Length (mm)", y = "Weight (g)", caption = "Gregory, S.V. and I. Arismendi. 2020. https://doi.org/10.6073/pasta/7c78d662e847cdbe33584add8f809165")+
  scale_color_manual(values = c("paleturquoise4", "skyblue4", "thistle4")) +
  facet_wrap(~reach) +
  theme_solarized()+
    theme(legend.position = "none")
cutthroat_size
ggsave(here::here("figs", "cutthroat_size.png"))
```

